version: "3.7"

services:
  ecoissue:
    image: ecoissue:dev
    tty: true
    init: true
    ports:
      - 8000:8000
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: development
    #command: sleep infinity
    command: bash -c "poetry install && poetry run uvicorn --factory ecoissue.main:app --reload --host 0.0.0.0 --port 8000"
    volumes:
      - ../ecoissue:/src